config/routes.rb
Weatherman::Application.routes.draw do
  devise_for :users

  get "weather_stations/index"

  get "weather_stations/show"

  match 'current_conditions(.:format)' => 'weather#current_conditions', :as => :current_conditions
  match 'forecast(.:format)' => 'weather#forecast', :as => :forecast

  resources :weather_stations
  
  root :to => 'weather_stations#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/weather_station.rb
class WeatherStation < ActiveRecord::Base
  ###############################################
  # Validations
  validates_uniqueness_of :identifier
  
  ###############################################
  # Geocoding
  reverse_geocoded_by :latitude, :longitude
  # after_validation :reverse_geocode  # auto-fetch address
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController

  
  # GET /current_conditions?lat=XX&lon=XX
  def current_conditions
    lat = params[:lat].to_f
    lon = params[:lon].to_f
    weather_station = WeatherStation.near([lat, lon], 10).all.first
    
    # Pull current conditions as hash
    current_conditions = {}
    if weather_station.nil?
      current_conditions = {:error => "No station found near #{lat}, #{lon}"}
    else
      current_conditions = pull_current_conditions weather_station.xml_url
    end

    #
    render :json => current_conditions # weather_station
  end
  
  # Forecase
  def forecast
    lat = params[:lat].to_f
    lon = params[:lon].to_f
    begin_date = params[:begin]
    end_date = params[:end]
    
    # Pull forecast as hash
    forecast = pull_forecast lat, lon, begin_date, end_date

    #
    render :json => forecast # weather_station
  end
  
  ###############################################
  private
  
  def pull_current_conditions xml_url
    logger.debug 'Fetching: ' + xml_url
    
    # Default return
    conditions = {:error => 'Unable to fetch current conditions.'} 
      
    # Create a Hydra to handle our requests
    hydra = Typhoeus::Hydra.new
    
    # Build the request object
    request = Typhoeus::Request.new(xml_url, 
                                    :method => :get, 
                                    :follow_location => true)
    
    # Setup the completion handler                                
    request.on_complete do |response|
      if response.success?
        REXML::Document.new(response.body)
        conditions = Hash.from_xml(response.body)
        conditions = conditions['current_observation'] if conditions
      elsif response.timed_out?
        logger.error 'HTTP Request Timed Out'
      elsif response.code == 0
        logger.error 'HTTP Request Failed: ' + response.curl_error_message
      else
        logger.error 'HTTP Request Failed: ' + response.code.to_s
      end
    end
    
    # Queue, then run the request
    hydra.queue request
    hydra.run

    conditions # return the weather conditions
  end
  
  ###############################################
  # Forecast
  def pull_forecast lat, lon, begin_date = DateTime.now, end_date=DateTime.now
    logger.debug "Fetching forecast: #{lat}, #{lon}"
    
    build_url = "http://graphical.weather.gov/xml/SOAP_server/ndfdXMLclient.php?whichClient=NDFDgen&lat=#{lat}&lon=#{lon}&listLatLon=&lat1=&lon1=&lat2=&lon2=&resolutionSub=&listLat1=&listLon1=&listLat2=&listLon2=&resolutionList=&endPoint1Lat=&endPoint1Lon=&endPoint2Lat=&endPoint2Lon=&listEndPoint1Lat=&listEndPoint1Lon=&listEndPoint2Lat=&listEndPoint2Lon=&zipCodeList=&listZipCodeList=&centerPointLat=&centerPointLon=&distanceLat=&distanceLon=&resolutionSquare=&listCenterPointLat=&listCenterPointLon=&listDistanceLat=&listDistanceLon=&listResolutionSquare=&citiesLevel=&listCitiesLevel=&sector=&gmlListLatLon=&featureType=&requestedTime=&startTime=&endTime=&compType=&propertyName=&product=glance&begin=#{begin_date}&end=#{end_date}&Unit=e&wx=wx&Submit=Submit"
    
    logger.debug "Pulling forecast from #{build_url}"
    
    # Default return
    forecast = {:error => 'Unable to fetch forecast.'} 
    
    # Create a Hydra to handle our requests
    hydra = Typhoeus::Hydra.new
    
    # Build the request object
    request = Typhoeus::Request.new(build_url,  
                                    :follow_location => true)
    
    # Setup the completion handler                                
    request.on_complete do |response|
      if response.success?
        REXML::Document.new(response.body)
        forecast = Hash.from_xml(response.body)
        forecast = forecast['dwml'] if forecast['dwml']
        forecast = forecast['data'] if forecast['data']
      elsif response.timed_out?
        logger.error 'HTTP Request Timed Out'
      elsif response.code == 0
        logger.error 'HTTP Request Failed: ' + response.curl_error_message
      else
        logger.error 'HTTP Request Failed: ' + response.code.to_s
      end
    end
    
    # Queue, then run the request
    hydra.queue request
    hydra.run

    forecast # return the forecast
  end
  
end

app/controllers/weather_stations_controller.rb
class WeatherStationsController < ApplicationController
  def index
    @weather_stations = WeatherStation.paginate(:page => params[:page])
  end

  def show
    @weather_station = WeatherStation.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title title
    content_for :title, title
  end
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/helpers/weather_stations_helper.rb
module WeatherStationsHelper
end

app/views/layouts/_footer.html.haml
%hr
%p
	&copy;2011 jessecurry |
	= link_to 'jesse@jessecurry.net', 'mailto:jesse@jessecurry.net' 

app/views/layouts/_header.html.haml
.header-content
  %ul#top
    %li
      = link_to '/' do
        %span.aboutus.sprite
          = image_tag 'spacer.gif', :width => 12, :height => 12
        = 'Home'
    %li
      - if user_signed_in?
        = "Signed in as #{current_user.email}. Not you?"
        = link_to "Sign out", destroy_user_session_path, :method => :delete
      - else
        = link_to "Sign up", new_user_registration_path
        or
        = link_to "Sign in", new_user_session_path
  .sub-logo
  .clearfix
  %ul#main-nav= render :partial => 'layouts/menu'
  

app/views/layouts/_menu.html.haml
%li 
  = link_to 'Weather Stations', weather_stations_path

app/views/layouts/_notices.html.haml
- if flash[:alert]
	%p{ :class => 'flash-error' }
		= flash[:alert]
- if flash[:notice]
	%p{ :class => 'flash-notice' }
		= flash[:notice]

app/views/layouts/application.html.haml
!!!
%html.no-js{:lang => "en"}
	%head
		%meta{ :charset => "utf-8" }
		%meta{ :content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible" }
		%link{ :rel => "shortcut icon", :href => "/favicon.ico", :type => "image/x-icon" }
		%title= "WeatherMan: " + (yield :title)
		%meta{ :content => "A Better NOAA Weather API", :name => "description" }
		%meta{ :content => "jessecurry", :name => "author" }
		%meta{ :content => "width=device-width,initial-scale=1", :name => "viewport" }
		= javascript_include_tag :defaults
	%body
		#container
			%section
				%header
					= render :partial => 'layouts/header'
			#main{ :role => "main" }= yield
			.clearfix
			#btm
			%footer{:id => 'btm'}
				= render :partial => 'layouts/footer'
			%section
				= render :partial => 'layouts/notices'

app/views/weather_stations/index.html.haml
- title 'Weather Stations'
.weather-stations
  - @weather_stations.each do |weather_station|
    .weather-station
      = link_to "#{weather_station.name}(#{weather_station.identifier})", weather_station
= will_paginate @weather_stations

app/views/weather_stations/show.html.haml
- title @weather_station.name
.weather-station
  .information
    = "#{@weather_station.name}(#{@weather_station.identifier})"
    = @weather_station.state
    = link_to 'html', @weather_station.html_url
    = link_to 'rss', @weather_station.rss_url
    = link_to 'xml', @weather_station.xml_url
  .map
    - if @weather_station.latitude && @weather_station.longitude
      .map-container
        = image_tag "http://maps.google.com/maps/api/staticmap?size=300x300&sensor=false&zoom=8&markers=#{@weather_station.latitude}%2C#{@weather_station.longitude}"